
--a)
SELECT d.PROFESOR, d.DEPARTAMENTO FROM D 
LEFT JOIN I  ON d.PROFESOR = i.PROFESOR WHERE i.PROFESOR IS NULL;

--b) 
SELECT d.PROFESOR, d.DEPARTAMENTO
FROM D  JOIN I  ON d.PROFESOR = i.PROFESOR
GROUP BY d.PROFESOR, d.DEPARTAMENTO HAVING COUNT(DISTINCT i.MODULO) = 2;

--c)
SELECT d.DEPARTAMENTO, COUNT(DISTINCT e.CICLO) as num_ciclos
FROM D  JOIN I  ON d.PROFESOR = i.PROFESOR
JOIN E  on i.MODULO = e.MODULO
GROUP BY d.DEPARTAMENTO HAVING COUNT(DISTINCT e.CICLO) > 1;

--d)

select  m.ALUMNO
FROM M 
GROUP BY m.ALUMNO HAVING MIN(m.NOTA) >= 5.00;

--e) 
 

--f)
select e.Modulo FROM e  WHERE e.CICLO='DAW';

 